hw-6
vasileuski/ts-react-course pull request #6
Opened 2022-08-28 12:21 UTC by vasileuski

2022-08-29 07:21 UTC, dromanchuck requested changes

2022-08-29 07:21 UTC, dromanchuck commented on hw-6/src/components/Clicker/index.tsx
> +      </button>
здесь надо было прятать кнопку если значение больше 10

```jsx
{value > 10 ?  (<button
        className={style.clicker__button}
        onClick={() => setValue(value + 1)}
      >
        +1
      </button>) : null}

```

2022-08-29 07:21 UTC, dromanchuck commented on hw-6/src/components/Clicker/index.tsx
> +      </button>
здесь то же самое, по условию 
`значения кликера меньше или равно 0, то нужно спрятать кнопку "-".`

2022-08-29 07:21 UTC, dromanchuck commented on hw-6/src/App.tsx
> +        <Card card={cards[0]} />
это должно быть в отдельном компоненте
и отрисовка списка должна быть при помощи map
[смотри тут](https://github.com/dromanchuck/tms-lessons/blob/main/classWork/src/components/TodoList/List/index.tsx)

2022-08-29 07:25 UTC, dromanchuck requested changes
и еще занеси файл  .DS_Store в gitignore

2022-08-30 19:39 UTC, vasileuski commented
Я исправил ошибки и сделал чуть получше. 
У меня не получилось сделать полноценный поиск. И на записи занятия не виден Сашин экран(

2022-08-31 15:16 UTC, dromanchuck approved these changes

2022-09-01 09:49 UTC, merged